{% set name = "pyshark" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshark-{{ version }}.tar.gz
  sha256: 6d0ab6e5522b134a7b1fbaaa46595e94ed33caac245f34e5a0234e13a0634c4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - py
    - packaging
    - python >=3.6

test:
  imports:
    - pyshark
    - pyshark.capture
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KimiNewt/pyshark
  summary: Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
