{% set name = "pyshark" %}
{% set version = "0.4.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshark-{{ version }}.tar.gz
  sha256: 8c38864ca26dd212980b8e054eb2238449e9b74af14dfe6c0e5a43b2d4336a52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lxml
    - py
    - python >=3.6

test:
  imports:
    - pyshark
    - pyshark.capture
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KimiNewt/pyshark
  summary: Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
